/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_regain_crawler_preparator_ifilter_IfilterWrapper */

#ifndef _Included_net_sf_regain_crawler_preparator_ifilter_IfilterWrapper
#define _Included_net_sf_regain_crawler_preparator_ifilter_IfilterWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_sf_regain_crawler_preparator_ifilter_IfilterWrapper
 * Method:    doCoInitialize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_sf_regain_crawler_preparator_ifilter_IfilterWrapper_doCoInitialize
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_sf_regain_crawler_preparator_ifilter_IfilterWrapper
 * Method:    doCoUninitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_regain_crawler_preparator_ifilter_IfilterWrapper_doCoUninitialize
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_regain_crawler_preparator_ifilter_IfilterWrapper
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_sf_regain_crawler_preparator_ifilter_IfilterWrapper_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_regain_crawler_preparator_ifilter_IfilterWrapper
 * Method:    getText
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_net_sf_regain_crawler_preparator_ifilter_IfilterWrapper_getText
  (JNIEnv *, jobject, jstring, jobject, jboolean);

/*
 * Class:     net_sf_regain_crawler_preparator_ifilter_IfilterWrapper
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_regain_crawler_preparator_ifilter_IfilterWrapper_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
